---
name: Text-NeatTemplate
version: 0.08
author:
  - Kathryn Andersen
abstract: 'a fast, middleweight template engine.'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Text::NeatTemplate:
    file: lib/Text/NeatTemplate.pm
    version: 0.08
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
